# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
import base64

# Greek text to encrypt
greek_text = "Αυτή είναι μια δοκιμή"

# Proper encoding
encoded_text = greek_text.encode('utf-8')

# 16-byte key and IV
key = b"thisis16bytekey!"   # 16 bytes
iv  = b"thisis16byteiv!!"   # 16 bytes

# Encrypt
cipher = AES.new(key, AES.MODE_CBC, iv)
ciphertext = cipher.encrypt(pad(encoded_text, AES.block_size))

ciphertext_base64 = base64.b64encode(ciphertext).decode('utf-8')
print("Encrypted (Base64):", ciphertext_base64)

# Decrypt
cipher = AES.new(key, AES.MODE_CBC, iv)
decrypted_text = unpad(cipher.decrypt(base64.b64decode(ciphertext_base64)), AES.block_size)

decoded_text = decrypted_text.decode('utf-8')
print("Decrypted Text:", decoded_text)

####################################################3
Encrypted (Base64): JnyZQzUU7khCGXXuFNpVAbcnsTgxlt/NZKGFU5KYC8DnYWbRApOjz78YBx11PZID
Decrypted Text: Αυτή είναι μια δοκιμή

